In [1]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import os
from PIL import Image


In [3]:
def load_images_from_folder(folder):
    images = []
    for filename in os.listdir(folder):
        img = Image.open(os.path.join(folder,filename))
        if img is not None:
            images.append(np.array(img))
    return images

In [8]:
monument_folder = 'D:/WORKSPACE/CNN_Project/Dataset/Indian-monuments/images/train/tajmahal'
#print(monument_folder)
monument_images = load_images_from_folder(monument_folder)

D:/WORKSPACE/CNN_Project/Dataset/Indian-monuments/images/train/tajmahal


In [9]:
for element in monument_images:
    print(element)

[[[106  66 128]
  [107  67 129]
  [107  67 129]
  ...
  [173 135 176]
  [173 135 176]
  [173 135 176]]

 [[107  67 129]
  [107  67 129]
  [108  68 130]
  ...
  [171 133 174]
  [171 133 174]
  [172 134 175]]

 [[106  67 130]
  [106  67 130]
  [107  68 131]
  ...
  [169 131 172]
  [169 131 172]
  [170 132 173]]

 ...

 [[134  88  65]
  [128  82  59]
  [130  85  62]
  ...
  [ 72  39  30]
  [ 76  43  34]
  [ 82  52  42]]

 [[141  95  71]
  [146 100  76]
  [145 101  76]
  ...
  [ 91  52  45]
  [104  67  59]
  [ 92  55  47]]

 [[139  92  66]
  [142  96  70]
  [132  88  61]
  ...
  [ 89  44  41]
  [ 91  46  43]
  [ 93  48  42]]]
[[[163 110  58]
  [166 114  64]
  [178 127  80]
  ...
  [170 171 189]
  [123 123 147]
  [ 82  82 106]]

 [[183 131  81]
  [186 136  87]
  [190 142  96]
  ...
  [110 112 127]
  [129 130 151]
  [175 173 195]]

 [[184 137  91]
  [192 145 101]
  [195 150 109]
  ...
  [104 104 116]
  [ 90  89 105]
  [108 105 122]]

 ...

 [[ 74  70   9]
  [ 88  84  20]
  [ 75  72   3]
  ..

In [ ]:
def load_data_from_folder(main_folder):
    all_data = []
    labels = []
    for idx, monument_folder in enumerate(os.listdir(main_folder)):
        monument_images = load_images_from_folder(os.path.join(main_folder, monument_folder))
        all_data += monument_images
        labels += [idx]*len(monument_images)
    return all_data, labels

In [ ]:
train_folder = 'path_to_your_train_folder'
train_data, train_labels = load_data_from_folder(train_folder)

In [ ]:
test_folder = 'path_to_your_test_folder'
test_data, test_labels = load_data_from_folder(test_folder)

In [ ]:
train_data = np.array(train_data)
train_labels = np.array(train_labels)
test_data = np.array(test_data)
test_labels = np.array(test_labels)